// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart"
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfbY3LSkmostNFBJgtI4JmjELWDtdPfqM',
    appId: '1:638658007004:web:b7a7928cfa1266ca5ac919',
    messagingSenderId: '638658007004',
    projectId: 'first-project-ca9e5',
    authDomain: 'first-project-ca9e5.firebaseapp.com',
    storageBucket: 'first-project-ca9e5.firebasestorage.app',
    measurementId: 'G-MR9WSF5CKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpQMejGGWP5fKTmBM17rS3473G0O1ClQI',
    appId: '1:638658007004:android:a1895d41fdf365155ac919',
    messagingSenderId: '638658007004',
    projectId: 'first-project-ca9e5',
    storageBucket: 'first-project-ca9e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO2mRa3jn_EMUMXG3DwVgCwSh0b1LDek0',
    appId: '1:638658007004:ios:656546773b93a7f75ac919',
    messagingSenderId: '638658007004',
    projectId: 'first-project-ca9e5',
    storageBucket: 'first-project-ca9e5.firebasestorage.app',
    iosBundleId: 'com.example.loginFoam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO2mRa3jn_EMUMXG3DwVgCwSh0b1LDek0',
    appId: '1:638658007004:ios:656546773b93a7f75ac919',
    messagingSenderId: '638658007004',
    projectId: 'first-project-ca9e5',
    storageBucket: 'first-project-ca9e5.firebasestorage.app',
    iosBundleId: 'com.example.loginFoam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfbY3LSkmostNFBJgtI4JmjELWDtdPfqM',
    appId: '1:638658007004:web:2269971b0a75dc6e5ac919',
    messagingSenderId: '638658007004',
    projectId: 'first-project-ca9e5',
    authDomain: 'first-project-ca9e5.firebaseapp.com',
    storageBucket: 'first-project-ca9e5.firebasestorage.app',
    measurementId: 'G-L2FEJ31KM2',
  );

}